### ISSUE TITLE
gulp build fails because of gremlin-core-js

### ISSUE THREAD

**Issue by mbghsource** [jbmusso/gremlin-sigma#1]
On a Lubuntu 16.04

~/git/gremlin-sigma$ node -v
v4.2.6

~/git/gremlin-sigma$ npm -v
3.5.2

after git clone, and npm install, gulp build fails

~/git/gremlin-sigma$ gulp build
[02:35:09] Using gulpfile ~/git/gremlin-sigma/Gulpfile.js
[02:35:09] Starting 'build'...
[02:35:09] Finished 'build' after 12 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: module "gremlin-core-js/src/structure/graph" not found from "/home/weberon/git/gremlin-sigma/src/structure/SigmaGraph.js"
    at notFound (/home/weberon/git/gremlin-sigma/node_modules/browserify/index.js:803:15)
    at /home/weberon/git/gremlin-sigma/node_modules/browserify/index.js:754:23
    at /home/weberon/git/gremlin-sigma/node_modules/browser-resolve/index.js:185:24
    at /home/weberon/git/gremlin-sigma/node_modules/browser-resolve/node_modules/resolve/lib/async.js:44:14
    at process (/home/weberon/git/gremlin-sigma/node_modules/browser-resolve/node_modules/resolve/lib/async.js:113:43)
    at /home/weberon/git/gremlin-sigma/node_modules/browser-resolve/node_modules/resolve/lib/async.js:122:21
    at load (/home/weberon/git/gremlin-sigma/node_modules/browser-resolve/node_modules/resolve/lib/async.js:54:43)
    at /home/weberon/git/gremlin-sigma/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:22
    at /home/weberon/git/gremlin-sigma/node_modules/browser-resolve/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by mbghsource** [comment]
The problem seems to be because of modules not being found due the js files being named in camelcase, whereas the module name in require(<module>) is all in lowercase.
